---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: online-boutique
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./kustomize
  prune: true
  sourceRef:
    kind: GitRepository
    name: online-boutique-source
  targetNamespace: default
  patches:
    - patch: |-
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: frontend
          namespace: default
        spec:
          template:
            spec:
              containers:
                - name: server
                  env:
                    - name: ENV_PLATFORM
                      value: "azure"