---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: online-boutique-source
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: main
  url: https://github.com/GoogleCloudPlatform/microservices-demo
